In [2]:
import numpy as np

In [3]:
# Throwing a coin 1 time: 0 is a tail, 1 heads
np.random.randint(low=0,high=2,size=1)        # hihg is non-inclusive

array([0])

In [13]:
# Throwing a coun 10 times: 0 is tail, 1 is heads
experiment = np.random.randint(0,2,size=10)
print(experiment)
print(experiment.sum())

[1 0 0 1 0 1 0 1 0 1]
5


In [8]:
# Each column of this matrix will be one 10-tosses simulaion
coin_matrix = np.random.randint(0,2,size=(1000,10))
coin_matrix[:5,:]

array([[0, 0, 1, 0, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 1, 0, 1]])

In [12]:
counts = coin_matrix.sum(axis=1)
print(counts[:25])
print(counts.mean())
print(np.median(counts))
print(counts.min(), counts.max())
print(counts.std())

[5 7 7 6 4 3 7 7 4 6 6 6 5 4 2 5 5 5 3 4 5 3 2 5 3]
5.074
5.0
0 10
1.5876158225465002
