In [ ]:
distances = [10,15,17,26,20]
times = [0.3,0.47,0.55,1.20,1.0]

In [ ]:
# Calculate Speeds with Python 
speeds = []
for i in range(len(distances)):
    speeds.append(distances[i]/times[i])
    
speeds

In [ ]:
[d/t for d,t in zip(distances, times)]

In [ ]:
product_quantities = [13,5,6,10,11]
prices = [1.2,6.5,1.0,4.8,5.0]
total = sum([q*p for p,q in zip(product_quantities, prices)])
total

In [ ]:
speeds = distances/times
total = (product_quantities*prices).sum()

# 1.2 Createing Numpy arrays
Vectorisation means; on an array like object , doing operations element by element.

# 2 Numpy arrays: Creation, methods and attributes
## What is a Numpy Array?
NumPy's main object is the homogeneous multidimentional array. It is a table of elements (usually numbers), all of the same type indexed by a tuple of positve integes. In NumPy **dimensions** are calles **axes**. The **number of axes is the rank or dimension.**

In [1]:
import numpy as np

## 2.2 Creating arrays, from lists and using built-in functions

In [2]:
# arrays from lists
distances = [10,15,17,26,20]
times = [0.3,0.47,0.55,1.20,1.0]
distances = np.array([distances])
times = np.array(prices)

NameError: name 'prices' is not defined

In [19]:
product_quantities = [13,5,6,10,11]
prices = [1.2,6.5,1.0,4.8,5.0]
product_quantities - np.array(product_quantities)
prices = np.array(prices)

In [20]:
distances

array([[10, 15, 17, 26, 20]])

In [21]:
type(distances)

numpy.ndarray

If we pass np.array() a lost of lists, it will create a 2-dimensional array. If we pass a list of lists , it will create a 3-dimensional array, and so n and so forth.

In [22]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [23]:
# Create a Length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
# Create a 3x5 floating-point array filled with ones 

np.ones(shape=(3,5), dtype = float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2

np.arange(start = 0, stop = 20, step =2) # step default is 1. Non-inclusive 


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
# create an array of 20 values evenly spaced between 0 and 1

np.linspace(0,1,20)  

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## 2.3 Some attributes of arrays

In [41]:
MyArray = np.ones(shape=(3,4), dtype=float)
MyArray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
MyArray.ndim   # dimensions

2

In [43]:
MyArray.shape   # x by y values

(3, 4)

In [40]:
MyArray.size    # total elements

12

## 2.4 Basic math with arrays

distances = [10,15,7,56,20]
times = [0.3,0.47,0.55,1.20,1.0]

In [44]:
speeds = distances/times
speeds

array([[ 8.33333333,  2.30769231, 17.        ,  5.41666667,  4.        ]])

product_quantities = [16,5,6,10,11]
prices = [1.2,6.5,1.0,4.8,5.0]

In [47]:
values = product_quantities*prices
total = values.sum()
print(values)
total

[15.6 32.5  6.  48.  55. ]


157.1

In [48]:
x = np.arange(start=0, stop=20, step=2)
x

# results below will be added to each element of the array


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
x + 1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [50]:
x * 2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [51]:
x/2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
# universal funtions
np.sin(x)   # Find the sin of each of the values in x

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [53]:
# universal funtions
np.exp(x)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07])

In [54]:
# universal funtions
np.log(x+1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

In [55]:
# universal funtions
np.sqrt(x)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

## 2.5 Common manipulations: indexing , slicing and reshaping

In [56]:
one_dim = np.linspace(-0.5, 0.6, 12)
one_dim

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [57]:
one_dim[0]    # zero based index

-0.5

In [58]:
one_dim[0] = 1
one_dim

array([ 1. , -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [62]:
two_dim = np.array([[3,5,2,4],[7,6,5,5,],[1,6,-1,-1]])
two_dim

array([[ 3,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

In [63]:
two_dim[0,3]   # from the 0th arrray, get the 4th item(3)

4

In [64]:
two_dim[0,0] = -1
two_dim

array([[-1,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

## 2.5.2 Slicing: Getting and setting smaller subarrays with a larger array

In [71]:
one_dim
for index ,value in enumerate(one_dim):
    print(index ,value)

0 1.0
1 -0.4
2 -0.3
3 -0.19999999999999996
4 -0.09999999999999998
5 0.0
6 0.10000000000000009
7 0.20000000000000007
8 0.30000000000000004
9 0.4
10 0.5
11 0.6


In [65]:
print(one_dim[2:5])   # same as siceing a regular python list
print(one_dim[:5])
print(one_dim[-5:])

[-0.3 -0.2 -0.1]
[ 1.  -0.4 -0.3 -0.2 -0.1]
[0.2 0.3 0.4 0.5 0.6]


In [74]:
two_dim

array([[-1,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

In [73]:
two_dim[:2,:2]

array([[-1,  5],
       [ 7,  6]])

In [72]:
two_dim[:,1:3]    # for every row , return fron index 1 to index 3

array([[ 5,  2],
       [ 6,  5],
       [ 6, -1]])

## 2.5.3 Reshaping of arrays: Changing the shape of a given array

In [77]:
one_dim

array([ 1. , -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [82]:
one_dim.reshape(2,2,3)

array([[[ 1. , -0.4, -0.3],
        [-0.2, -0.1,  0. ]],

       [[ 0.1,  0.2,  0.3],
        [ 0.4,  0.5,  0.6]]])

In [80]:
two_dim

array([[-1,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

In [83]:
two_dim.flatten()

array([-1,  5,  2,  4,  7,  6,  5,  5,  1,  6, -1, -1])